version: '3.7'

services:
  web:
    build: 
      context: ./services/web
      dockerfile: Dockerfile
    command: gunicorn manage:app --bind 0.0.0.0:1776 --reload
    ports:
      - 1776:1776
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
